#!/usr/bin/env bash

# Magnitude of earthquakes worldwide 2.5 and above in the last 24 hours:
curl -s https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.csv |
  sed '1d' |
  cut -d, -f5 |
  spark